// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDagdKBXA2qaspw0mKb_Gm7L39zQpuFDos',
    appId: '1:208131680490:web:650cf2c2789b2a23460f93',
    messagingSenderId: '208131680490',
    projectId: 'tagfootstats',
    authDomain: 'tagfootstats.firebaseapp.com',
    storageBucket: 'tagfootstats.firebasestorage.app',
    measurementId: 'G-X86X5YLMRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0-fSqHIk3lhcjgrokDdros0CM-CVsi-k',
    appId: '1:208131680490:android:5a928e64c1521424460f93',
    messagingSenderId: '208131680490',
    projectId: 'tagfootstats',
    storageBucket: 'tagfootstats.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2WCkaVIMsoxHLFENv_RGWOsdN7l9gU5o',
    appId: '1:208131680490:ios:6010d2521583c508460f93',
    messagingSenderId: '208131680490',
    projectId: 'tagfootstats',
    storageBucket: 'tagfootstats.firebasestorage.app',
    iosBundleId: 'com.example.tagfootstats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2WCkaVIMsoxHLFENv_RGWOsdN7l9gU5o',
    appId: '1:208131680490:ios:6010d2521583c508460f93',
    messagingSenderId: '208131680490',
    projectId: 'tagfootstats',
    storageBucket: 'tagfootstats.firebasestorage.app',
    iosBundleId: 'com.example.tagfootstats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDagdKBXA2qaspw0mKb_Gm7L39zQpuFDos',
    appId: '1:208131680490:web:9e2ae5373f5a6ed7460f93',
    messagingSenderId: '208131680490',
    projectId: 'tagfootstats',
    authDomain: 'tagfootstats.firebaseapp.com',
    storageBucket: 'tagfootstats.firebasestorage.app',
    measurementId: 'G-MDMRY5L957',
  );
}
